# Generated by Django 6.0.2 on 2026-03-03 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'insumo',
                'verbose_name_plural': 'insumos',
                'db_table': 'insumo',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('existencia', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'Producto',
            },
        ),
        migrations.CreateModel(
            name='tipo_servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('ACEITE', 'Cambio de aceite'), ('FILTROS', 'Cambio de filtros'), ('REVISION', 'Revisión general'), ('DIAGNOSTICO', 'Diagnóstico'), ('PREVENTIVO', 'Mantenimiento preventivo'), ('CORRECTIVO', 'Mantenimiento correctivo'), ('ALINEACION', 'Alineación y balanceo'), ('FRENOS', 'Servicio de frenos'), ('BATERIA', 'Cambio de batería'), ('ELECTRICO', 'Sistema eléctrico'), ('SUSPENSION', 'Suspensión'), ('DIRECCION', 'Dirección'), ('MOTOR', 'Reparación de motor'), ('SINCRONIZACION', 'Sincronización'), ('CORREA', 'Cambio de correa'), ('REFRIGERACION', 'Refrigeración'), ('AIRE', 'Aire acondicionado'), ('BUJIAS', 'Cambio de bujías'), ('LAVADO', 'Lavado'), ('INSPECCION', 'Inspección')], max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('MEC', 'Mecánica general'), ('ELEC', 'Electricidad automotriz'), ('FREN', 'Frenos'), ('SUSP', 'Suspensión'), ('MANT', 'Mantenimiento'), ('DIAG', 'Diagnóstico'), ('CLIM', 'Climatización'), ('EST', 'Estética vehicular')], max_length=100)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'tipo_servicio',
                'verbose_name_plural': 'tipo_servicios',
                'db_table': 'tipo_servicio',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('Administrador', 'Administrador'), ('Usuario', 'Usuario')], max_length=45)),
                ('telefono', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45, unique=True)),
                ('direccion', models.CharField(max_length=100)),
                ('contrasena', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='Entrada_vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_entrada', models.DateTimeField(auto_now_add=True)),
                ('placa', models.CharField(max_length=6)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
            ],
            options={
                'verbose_name': 'Entrada de Vehículo',
                'verbose_name_plural': 'Entradas de Vehículos',
                'db_table': 'entrada_vehiculos',
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
                ('fk_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producto')),
            ],
            options={
                'verbose_name': 'Categoría ',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('documento', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=100)),
                ('estado', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True)),
                ('mercancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producto')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'Proveedor',
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(max_length=10)),
                ('fk_insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.insumo')),
                ('fk_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.proveedor')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'db_table': 'compra',
            },
        ),
        migrations.CreateModel(
            name='Salida_vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_salida', models.DateTimeField()),
                ('total_a_pagar', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('entrada', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salida', to='app.entrada_vehiculo')),
            ],
            options={
                'verbose_name': 'Salida de Vehículo',
                'verbose_name_plural': 'Salidas de Vehículos',
                'db_table': 'salida_vehiculos',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='app.entrada_vehiculo')),
                ('insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.insumo')),
                ('tipo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipo_servicio')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.usuario')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'servicios',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_vehiculo', models.CharField(choices=[('Sedán', 'Sedán'), ('SUV', 'SUV'), ('Hatchback', 'Hatchback'), ('Coupé', 'Coupé'), ('Convertible', 'Convertible'), ('Pickup', 'Pickup'), ('Minivan', 'Minivan'), ('Station Wagon', 'Station Wagon'), ('Deportivo', 'Deportivo'), ('Crossover', 'Crossover')], max_length=100)),
                ('placa', models.CharField(max_length=6)),
                ('marca', models.CharField(max_length=100)),
                ('kilometraje', models.IntegerField()),
                ('modelo', models.CharField(max_length=30)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
            ],
            options={
                'verbose_name': 'Vehiculo',
                'verbose_name_plural': 'Vehiculos',
                'db_table': 'Vehiculo',
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
                ('productos', models.ManyToManyField(to='app.producto')),
                ('salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.salida_vehiculo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Venta',
                'db_table': 'Venta',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_notificacion', models.CharField(choices=[('Mensaje', 'Mensaje General'), ('Alerta', 'Alerta Importante'), ('Recordatorio', 'Recordatorio')])),
                ('mensaje', models.CharField(max_length=45)),
                ('fecha_envio', models.CharField(max_length=45)),
                ('ventas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ventas')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificacion',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ventas')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'Factura',
            },
        ),
    ]
