# Generated by Django 6.0.2 on 2026-02-27 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificacion',
            old_name='fk_ventas',
            new_name='ventas',
        ),
    ]
