# Generated by Django 6.0.2 on 2026-02-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada_vehiculo',
            name='documento',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='entrada_vehiculo',
            name='fecha_hora_entrada',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
