# Generated by Django 6.0.2 on 2026-02-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo_servicio',
            name='duracion_estimada',
        ),
        migrations.AddField(
            model_name='tipo_servicio',
            name='hora_entrada_estimada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tipo_servicio',
            name='hora_salida_estimada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='estado',
            field=models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True),
        ),
    ]
