# Generated by Django 6.0.2 on 2026-02-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='documento',
        ),
        migrations.AlterField(
            model_name='servicio',
            name='duracion',
            field=models.TimeField(),
        ),
    ]
